"""Realistic device templates configuration for Redroid fingerprint spoofing."""

from typing import List, Dict, Any

DEVICE_TEMPLATES: List[Dict[str, Any]] = [
    # --- SAMSUNG ---
    {
        "brand": "samsung",
        "manufacturer": "samsung",
        "model": "SM-S918B",
        "product": "dm3qxxx",
        "device": "dm3q",
        "board": "kalama",
        "hardware": "qcom",
        "fingerprint": "samsung/dm3qxxx/dm3q:13/TP1A.220624.014/S918BXXU1AWBD:user/release-keys",
    },
    {
        "brand": "samsung",
        "manufacturer": "samsung",
        "model": "SM-S911B",
        "product": "dm1qxxx",
        "device": "dm1q",
        "board": "kalama",
        "hardware": "qcom",
        "fingerprint": "samsung/dm1qxxx/dm1q:13/TP1A.220624.014/S911BXXU1AWBD:user/release-keys",
    },
    {
        "brand": "samsung",
        "manufacturer": "samsung",
        "model": "SM-S908B",
        "product": "b0qxxx",
        "device": "b0q",
        "board": "exynos2200",
        "hardware": "s5e9925",
        "fingerprint": "samsung/b0qxxx/b0q:12/SP1A.210812.016/S908BXXU2AVG6:user/release-keys",
    },
    {
        "brand": "samsung",
        "manufacturer": "samsung",
        "model": "SM-S901B",
        "product": "r0qxxx",
        "device": "r0q",
        "board": "exynos2200",
        "hardware": "s5e9925",
        "fingerprint": "samsung/r0qxxx/r0q:12/SP1A.210812.016/S901BXXU2AVG6:user/release-keys",
    },
    {
        "brand": "samsung",
        "manufacturer": "samsung",
        "model": "SM-G998B",
        "product": "p3sxxx",
        "device": "p3s",
        "board": "exynos2100",
        "hardware": "exynos2100",
        "fingerprint": "samsung/p3sxxx/p3s:11/RP1A.200720.012/G998BXXU3AUID:user/release-keys",
    },
    {
        "brand": "samsung",
        "manufacturer": "samsung",
        "model": "SM-G991B",
        "product": "o1sxxx",
        "device": "o1s",
        "board": "exynos2100",
        "hardware": "exynos2100",
        "fingerprint": "samsung/o1sxxx/o1s:11/RP1A.200720.012/G991BXXU5EWF1:user/release-keys",
    },
    {
        "brand": "samsung",
        "manufacturer": "samsung",
        "model": "SM-G780G",
        "product": "r8qxxx",
        "device": "r8q",
        "board": "kona",
        "hardware": "qcom",
        "fingerprint": "samsung/r8qxxx/r8q:11/RP1A.200720.012/G780GXXU3BVC2:user/release-keys",
    },
    {
        "brand": "samsung",
        "manufacturer": "samsung",
        "model": "SM-A546B",
        "product": "a54xnsxx",
        "device": "a54x",
        "board": "s5e8835",
        "hardware": "s5e8835",
        "fingerprint": "samsung/a54xnsxx/a54x:13/TP1A.220624.014/A546BXXU1AWCD:user/release-keys",
    },
    {
        "brand": "samsung",
        "manufacturer": "samsung",
        "model": "SM-A536B",
        "product": "a53xnsxx",
        "device": "a53x",
        "board": "s5e8825",
        "hardware": "s5e8825",
        "fingerprint": "samsung/a53xnsxx/a53x:12/SP1A.210812.016/A536BXXU1AVB7:user/release-keys",
    },
    {
        "brand": "samsung",
        "manufacturer": "samsung",
        "model": "SM-A528B",
        "product": "a52sxqxx",
        "device": "a52sxq",
        "board": "lahaina",
        "hardware": "qcom",
        "fingerprint": "samsung/a52sxqxx/a52sxq:11/RP1A.200720.012/A528BXXU1AUH9:user/release-keys",
    },
    {
        "brand": "samsung",
        "manufacturer": "samsung",
        "model": "SM-A346B",
        "product": "a34xeea",
        "device": "a34x",
        "board": "mt6877",
        "hardware": "mt6877",
        "fingerprint": "samsung/a34xeea/a34x:13/TP1A.220624.014/A346BXXU1AWB9:user/release-keys",
    },
    {
        "brand": "samsung",
        "manufacturer": "samsung",
        "model": "SM-A336B",
        "product": "a33xnsxx",
        "device": "a33x",
        "board": "s5e8825",
        "hardware": "s5e8825",
        "fingerprint": "samsung/a33xnsxx/a33x:12/SP1A.210812.016/A336BXXU1AVB9:user/release-keys",
    },
    {
        "brand": "samsung",
        "manufacturer": "samsung",
        "model": "SM-A236B",
        "product": "a23xqxx",
        "device": "a23xq",
        "board": "holi",
        "hardware": "qcom",
        "fingerprint": "samsung/a23xqxx/a23xq:12/SP1A.210812.016/A236BXXU1AVG8:user/release-keys",
    },
    {
        "brand": "samsung",
        "manufacturer": "samsung",
        "model": "SM-A146P",
        "product": "a14xeea",
        "device": "a14x",
        "board": "mt6833",
        "hardware": "mt6833",
        "fingerprint": "samsung/a14xeea/a14x:13/TP1A.220624.014/A146PXXU1AWA2:user/release-keys",
    },
    {
        "brand": "samsung",
        "manufacturer": "samsung",
        "model": "SM-F936B",
        "product": "q4qxxx",
        "device": "q4q",
        "board": "taro",
        "hardware": "qcom",
        "fingerprint": "samsung/q4qxxx/q4q:12/SP1A.210812.016/F936BXXU1AVGA:user/release-keys",
    },
    {
        "brand": "samsung",
        "manufacturer": "samsung",
        "model": "SM-F721B",
        "product": "b4qxxx",
        "device": "b4q",
        "board": "taro",
        "hardware": "qcom",
        "fingerprint": "samsung/b4qxxx/b4q:12/SP1A.210812.016/F721BXXU1AVGA:user/release-keys",
    },
    {
        "brand": "samsung",
        "manufacturer": "samsung",
        "model": "SM-N986B",
        "product": "c2sxxx",
        "device": "c2s",
        "board": "exynos990",
        "hardware": "exynos990",
        "fingerprint": "samsung/c2sxxx/c2s:11/RP1A.200720.012/N986BXXU3DUF4:user/release-keys",
    },

    # --- GOOGLE PIXEL ---
    {
        "brand": "google",
        "manufacturer": "Google",
        "model": "Pixel 8 Pro",
        "product": "husky",
        "device": "husky",
        "board": "husky",
        "hardware": "zuma",
        "fingerprint": "google/husky/husky:14/UD1A.230803.041/10798224:user/release-keys",
    },
    {
        "brand": "google",
        "manufacturer": "Google",
        "model": "Pixel 8",
        "product": "shiba",
        "device": "shiba",
        "board": "shiba",
        "hardware": "zuma",
        "fingerprint": "google/shiba/shiba:14/UD1A.230803.041/10798224:user/release-keys",
    },
    {
        "brand": "google",
        "manufacturer": "Google",
        "model": "Pixel 7 Pro",
        "product": "cheetah",
        "device": "cheetah",
        "board": "cheetah",
        "hardware": "cloudripper",
        "fingerprint": "google/cheetah/cheetah:13/TQ3A.230901.001/10750766:user/release-keys",
    },
    {
        "brand": "google",
        "manufacturer": "Google",
        "model": "Pixel 7",
        "product": "panther",
        "device": "panther",
        "board": "panther",
        "hardware": "cloudripper",
        "fingerprint": "google/panther/panther:13/TQ3A.230901.001/10750766:user/release-keys",
    },
    {
        "brand": "google",
        "manufacturer": "Google",
        "model": "Pixel 7a",
        "product": "lynx",
        "device": "lynx",
        "board": "lynx",
        "hardware": "cloudripper",
        "fingerprint": "google/lynx/lynx:13/TQ3A.230805.001/10316538:user/release-keys",
    },
    {
        "brand": "google",
        "manufacturer": "Google",
        "model": "Pixel 6 Pro",
        "product": "raven",
        "device": "raven",
        "board": "raven",
        "hardware": "tensor",
        "fingerprint": "google/raven/raven:12/SQ3A.220705.004/8694371:user/release-keys",
    },
    {
        "brand": "google",
        "manufacturer": "Google",
        "model": "Pixel 6",
        "product": "oriole",
        "device": "oriole",
        "board": "oriole",
        "hardware": "tensor",
        "fingerprint": "google/oriole/oriole:12/SQ3A.220705.004/8694371:user/release-keys",
    },
    {
        "brand": "google",
        "manufacturer": "Google",
        "model": "Pixel 6a",
        "product": "bluejay",
        "device": "bluejay",
        "board": "bluejay",
        "hardware": "tensor",
        "fingerprint": "google/bluejay/bluejay:12/SD2A.220601.003/8597282:user/release-keys",
    },
    {
        "brand": "google",
        "manufacturer": "Google",
        "model": "Pixel 5",
        "product": "redfin",
        "device": "redfin",
        "board": "redfin",
        "hardware": "qcom",
        "fingerprint": "google/redfin/redfin:11/RQ3A.211001.001/7641976:user/release-keys",
    },
    {
        "brand": "google",
        "manufacturer": "Google",
        "model": "Pixel 4a",
        "product": "sunfish",
        "device": "sunfish",
        "board": "sunfish",
        "hardware": "qcom",
        "fingerprint": "google/sunfish/sunfish:11/RQ3A.210905.001/7511028:user/release-keys",
    },

    # --- XIAOMI / REDMI / POCO ---
    {
        "brand": "Xiaomi",
        "manufacturer": "Xiaomi",
        "model": "2210132C",
        "product": "nuwa",
        "device": "nuwa",
        "board": "taro",
        "hardware": "qcom",
        "fingerprint": "Xiaomi/nuwa/nuwa:13/TKQ1.220829.002/V14.0.4.0.TMBCNXM:user/release-keys",
    },
    {
        "brand": "Xiaomi",
        "manufacturer": "Xiaomi",
        "model": "2211133G",
        "product": "fuxi_global",
        "device": "fuxi",
        "board": "taro",
        "hardware": "qcom",
        "fingerprint": "Xiaomi/fuxi_global/fuxi:13/TKQ1.220829.002/V14.0.19.0.TMCMIXM:user/release-keys",
    },
    {
        "brand": "Xiaomi",
        "manufacturer": "Xiaomi",
        "model": "2201122G",
        "product": "zeus_global",
        "device": "zeus",
        "board": "taro",
        "hardware": "qcom",
        "fingerprint": "Xiaomi/zeus_global/zeus:12/SKQ1.211006.001/V13.0.10.0.SLBMIXM:user/release-keys",
    },
    {
        "brand": "Xiaomi",
        "manufacturer": "Xiaomi",
        "model": "2201123G",
        "product": "cupid_global",
        "device": "cupid",
        "board": "taro",
        "hardware": "qcom",
        "fingerprint": "Xiaomi/cupid_global/cupid:12/SKQ1.211006.001/V13.0.12.0.SLCMIXM:user/release-keys",
    },
    {
        "brand": "Xiaomi",
        "manufacturer": "Xiaomi",
        "model": "2107113SG",
        "product": "vili_global",
        "device": "vili",
        "board": "lahaina",
        "hardware": "qcom",
        "fingerprint": "Xiaomi/vili_global/vili:11/RKQ1.200826.002/V12.5.8.0.RKDMIXM:user/release-keys",
    },
    {
        "brand": "Xiaomi",
        "manufacturer": "Xiaomi",
        "model": "21081111RG",
        "product": "agate_global",
        "device": "agate",
        "board": "agate",
        "hardware": "mt6893",
        "fingerprint": "Xiaomi/agate_global/agate:11/RP1A.200720.011/V12.5.4.0.RKWMIXM:user/release-keys",
    },
    {
        "brand": "Redmi",
        "manufacturer": "Xiaomi",
        "model": "22101316G",
        "product": "ruby_global",
        "device": "ruby",
        "board": "ruby",
        "hardware": "mt6877",
        "fingerprint": "Redmi/ruby_global/ruby:12/SP1A.210812.016/V14.0.1.0.SMOMIXM:user/release-keys",
    },
    {
        "brand": "Redmi",
        "manufacturer": "Xiaomi",
        "model": "22111317G",
        "product": "sunstone_global",
        "device": "sunstone",
        "board": "sunstone",
        "hardware": "qcom",
        "fingerprint": "Redmi/sunstone_global/sunstone:12/SKQ1.221110.001/V14.0.2.0.SMQMIXM:user/release-keys",
    },
    {
        "brand": "Redmi",
        "manufacturer": "Xiaomi",
        "model": "23021RAA2Y",
        "product": "tapas_global",
        "device": "tapas",
        "board": "tapas",
        "hardware": "qcom",
        "fingerprint": "Redmi/tapas_global/tapas:13/TKQ1.221114.001/V14.0.6.0.TMTMIXM:user/release-keys",
    },
    {
        "brand": "Redmi",
        "manufacturer": "Xiaomi",
        "model": "2201116SG",
        "product": "veux_global",
        "device": "veux",
        "board": "veux",
        "hardware": "qcom",
        "fingerprint": "Redmi/veux_global/veux:11/RKQ1.211119.001/V13.0.10.0.RKCMIXM:user/release-keys",
    },
    {
        "brand": "Redmi",
        "manufacturer": "Xiaomi",
        "model": "2201117TI",
        "product": "spes_global",
        "device": "spes",
        "board": "spes",
        "hardware": "qcom",
        "fingerprint": "Redmi/spes_global/spes:11/RKQ1.211119.001/V13.0.5.0.SKCMIXM:user/release-keys",
    },
    {
        "brand": "Redmi",
        "manufacturer": "Xiaomi",
        "model": "M2101K6G",
        "product": "sweet_global",
        "device": "sweet",
        "board": "sweet",
        "hardware": "qcom",
        "fingerprint": "Redmi/sweet_global/sweet:11/RKQ1.200826.002/V12.5.6.0.RKFMIXM:user/release-keys",
    },
    {
        "brand": "POCO",
        "manufacturer": "Xiaomi",
        "model": "23013PC75G",
        "product": "mondrian_global",
        "device": "mondrian",
        "board": "taro",
        "hardware": "qcom",
        "fingerprint": "POCO/mondrian_global/mondrian:13/TKQ1.220905.001/V14.0.4.0.TMNMIXM:user/release-keys",
    },
    {
        "brand": "POCO",
        "manufacturer": "Xiaomi",
        "model": "23049PCD8G",
        "product": "marble_global",
        "device": "marble",
        "board": "marble",
        "hardware": "qcom",
        "fingerprint": "POCO/marble_global/marble:13/TKQ1.221013.002/V14.0.2.0.TMRMIXM:user/release-keys",
    },
    {
        "brand": "POCO",
        "manufacturer": "Xiaomi",
        "model": "22101320G",
        "product": "redwood_global",
        "device": "redwood",
        "board": "redwood",
        "hardware": "qcom",
        "fingerprint": "POCO/redwood_global/redwood:12/SKQ1.220807.001/V14.0.1.0.SMSMIXM:user/release-keys",
    },
    {
        "brand": "POCO",
        "manufacturer": "Xiaomi",
        "model": "22021211RG",
        "product": "munch_global",
        "device": "munch",
        "board": "munch",
        "hardware": "qcom",
        "fingerprint": "POCO/munch_global/munch:12/SKQ1.211006.001/V13.0.2.0.SLMMIXM:user/release-keys",
    },

    # --- OPPO ---
    {
        "brand": "OPPO",
        "manufacturer": "OPPO",
        "model": "CPH2305",
        "product": "CPH2305",
        "device": "OP528BL1",
        "board": "taro",
        "hardware": "qcom",
        "fingerprint": "OPPO/CPH2305/OP528BL1:12/SKQ1.211113.001/1647432029:user/release-keys",
    },
    {
        "brand": "OPPO",
        "manufacturer": "OPPO",
        "model": "CPH2173",
        "product": "CPH2173",
        "device": "OP4E75L1",
        "board": "lahaina",
        "hardware": "qcom",
        "fingerprint": "OPPO/CPH2173/OP4E75L1:11/RKQ1.200928.002/1620392348:user/release-keys",
    },
    {
        "brand": "OPPO",
        "manufacturer": "OPPO",
        "model": "CPH2521",
        "product": "CPH2521",
        "device": "OP5945L1",
        "board": "taro",
        "hardware": "qcom",
        "fingerprint": "OPPO/CPH2521/OP5945L1:13/TP1A.220905.001/1689240892:user/release-keys",
    },
    {
        "brand": "OPPO",
        "manufacturer": "OPPO",
        "model": "CPH2525",
        "product": "CPH2525",
        "device": "OP5949L1",
        "board": "mt6877",
        "hardware": "mt6877",
        "fingerprint": "OPPO/CPH2525/OP5949L1:13/TP1A.220905.001/1687352341:user/release-keys",
    },
    {
        "brand": "OPPO",
        "manufacturer": "OPPO",
        "model": "CPH2357",
        "product": "CPH2357",
        "device": "OP5567L1",
        "board": "mt6895",
        "hardware": "mt6895",
        "fingerprint": "OPPO/CPH2357/OP5567L1:12/SP1A.210812.016/1657802341:user/release-keys",
    },
    {
        "brand": "OPPO",
        "manufacturer": "OPPO",
        "model": "CPH2371",
        "product": "CPH2371",
        "device": "OP535DL1",
        "board": "mt6877",
        "hardware": "mt6877",
        "fingerprint": "OPPO/CPH2371/OP535DL1:11/RP1A.200720.011/1643194821:user/release-keys",
    },
    {
        "brand": "OPPO",
        "manufacturer": "OPPO",
        "model": "CPH2483",
        "product": "CPH2483",
        "device": "OP584BL1",
        "board": "mt6833",
        "hardware": "mt6833",
        "fingerprint": "OPPO/CPH2483/OP584BL1:12/SP1A.210812.016/1672301290:user/release-keys",
    },
    {
        "brand": "OPPO",
        "manufacturer": "OPPO",
        "model": "CPH2333",
        "product": "CPH2333",
        "device": "OP5349L1",
        "board": "bengal",
        "hardware": "qcom",
        "fingerprint": "OPPO/CPH2333/OP5349L1:11/RKQ1.211119.001/1641829012:user/release-keys",
    },
    {
        "brand": "OPPO",
        "manufacturer": "OPPO",
        "model": "CPH2211",
        "product": "CPH2211",
        "device": "OP4F0B",
        "board": "oppo6877",
        "hardware": "mt6877",
        "fingerprint": "OPPO/CPH2211/OP4F0B:11/RP1A.200720.011/1654129845:user/release-keys",
    },

    # --- ONEPLUS ---
    {
        "brand": "OnePlus",
        "manufacturer": "OnePlus",
        "model": "CPH2449",
        "product": "CPH2449",
        "device": "OP594DL1",
        "board": "kalama",
        "hardware": "qcom",
        "fingerprint": "OnePlus/CPH2449/OP594DL1:13/TKQ1.221013.002/1673892011:user/release-keys",
    },
    {
        "brand": "OnePlus",
        "manufacturer": "OnePlus",
        "model": "NE2213",
        "product": "NE2213",
        "device": "OP515BL1",
        "board": "taro",
        "hardware": "qcom",
        "fingerprint": "OnePlus/NE2213/OP515BL1:12/SKQ1.211113.001/1647412984:user/release-keys",
    },
    {
        "brand": "OnePlus",
        "model": "LE2123",
        "manufacturer": "OnePlus",
        "product": "LE2123",
        "device": "OP48C5L1",
        "board": "lahaina",
        "hardware": "qcom",
        "fingerprint": "OnePlus/LE2123/OP48C5L1:11/RKQ1.201105.002/2103242100:user/release-keys",
    },
    {
        "brand": "OnePlus",
        "manufacturer": "OnePlus",
        "model": "CPH2493",
        "product": "CPH2493",
        "device": "OP5955L1",
        "board": "mt6983",
        "hardware": "mt6983",
        "fingerprint": "OnePlus/CPH2493/OP5955L1:13/TP1A.220905.001/1687391024:user/release-keys",
    },
    {
        "brand": "OnePlus",
        "manufacturer": "OnePlus",
        "model": "CPH2399",
        "product": "CPH2399",
        "device": "OP556BL1",
        "board": "mt6893",
        "hardware": "mt6893",
        "fingerprint": "OnePlus/CPH2399/OP556BL1:12/SP1A.210812.016/1652391023:user/release-keys",
    },

    # --- SONY & ASUS & NOTHING ---
    {
        "brand": "Sony",
        "manufacturer": "Sony",
        "model": "XQ-CT72",
        "product": "XQ-CT72",
        "device": "XQ-CT72",
        "board": "taro",
        "hardware": "qcom",
        "fingerprint": "Sony/XQ-CT72/XQ-CT72:12/61.1.A.9.128/061001A009012803272990022:user/release-keys",
    },
    {
        "brand": "Sony",
        "manufacturer": "Sony",
        "model": "XQ-CQ72",
        "product": "XQ-CQ72",
        "device": "XQ-CQ72",
        "board": "taro",
        "hardware": "qcom",
        "fingerprint": "Sony/XQ-CQ72/XQ-CQ72:12/64.0.A.11.31/064000A011003102482319011:user/release-keys",
    },
    {
        "brand": "asus",
        "manufacturer": "asus",
        "model": "ASUS_AI2201",
        "product": "WW_AI2201",
        "device": "AI2201",
        "board": "taro",
        "hardware": "qcom",
        "fingerprint": "asus/WW_AI2201/AI2201:12/SKQ1.211019.001/32.2810.2208.165-0:user/release-keys",
    },
    {
        "brand": "Nothing",
        "manufacturer": "Nothing",
        "model": "A063",
        "product": "Spacewar",
        "device": "Spacewar",
        "board": "lahaina",
        "hardware": "qcom",
        "fingerprint": "Nothing/Spacewar/Spacewar:12/SKQ1.211230.001/1657802341:user/release-keys",
    },
    {
        "brand": "Nothing",
        "manufacturer": "Nothing",
        "model": "A065",
        "product": "Pong",
        "device": "Pong",
        "board": "taro",
        "hardware": "qcom",
        "fingerprint": "Nothing/Pong/Pong:13/TKQ1.221114.001/1689240892:user/release-keys",
    },
]
